services:
  ############################
  # Dotnet app + Dapr sidecar
  ############################
  #dotnetapp:
  #  build:
  #    context: .
  #    dockerfile: ./Dockerfile
  #    args:
  #      - APP_NAME=StateManagement
  #  command: ["0"]
  #  depends_on:
  #    redis:
  #      condition: service_healthy
  #
  #dotnetapp-dapr:
  #  image: "daprio/daprd:edge"
  #  command: ["./daprd",
  #    "-app-id", "dotnetapp",
  #    "-components-path", "/components"]
  #  network_mode: "service:dotnetapp"
  #  volumes:
  #    - "./components/:/components"
  #  depends_on:
  #    redis:
  #      condition: service_healthy

  ############################
  # Dotnet app + Dapr sidecar
  ############################
  dotnetapp:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=StateManagement.Api
    environment:
      LOGGING__LOGLEVEL__DEFAULT: Warning
    ports:
      - "8080:8080"
    depends_on:
      cosmosdb:
        condition: service_healthy

  dotnetapp-dapr:
    image: "frundh/daprd:latest-linux-amd64"
    command: ["./daprd",
      "-app-id", "dotnetapp",
      "-components-path", "/components"]
    network_mode: "service:dotnetapp"
    volumes:
      - "./components/:/components"
    depends_on:
      cosmosdb:
        condition: service_healthy

  ############################
  # Redis state store
  ############################
  #redis:
  #  image: "redis:alpine"
  #  ports:
  #    - "6380:6379"
  #  healthcheck:
  #    test: ["CMD", "redis-cli", "ping"]
  #    interval: 10s
  #    timeout: 3s
  #    retries: 30

  ############################
  # CosmosDB emulator
  ############################
  cosmosdb:
    #image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator"
    build:
      context: ./cosmosdb
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Data explorer web UI (https://localhost:8081/_explorer/index.html)
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1

  ############################
  # Locust load testing
  ############################
  locust:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./locust/locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py
    environment:
      # https://docs.locust.io/en/stable/configuration.html
      #LOCUST_WEB_PORT: 8089
      LOCUST_USERS: 10
      LOCUST_AUTOSTART: false
    depends_on:
      dotnetapp:
        condition: service_started